list: $/szb/jegyzet/models/note/columns.yaml
modelClass: Szb\Jegyzet\Models\Note
title: NoteContoller
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'szb/jegyzet/notecontoller/update/:id'
